spring:
  datasource:
    username: root
    password: qwe10086
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/logstarter?serverTimezone=GMT%2B8

#sg:
#  log:
#    request:
#      enabled: true